### ISSUE TITLE
sample app using dex

### ISSUE THREAD

**Issue by baerae-colin** [klaytn/project-management#8]
1. study various dexes on Klaytn
1. learn how to deploy liquidity pool for the dexes
1. deploy ERC-20, KIP-7 token (consider proxy contract too)
1. make token transfer
1. setup liqudity pool ( it would be good if this can be done using caver)

**Comment by jimni1222** [comment]
I researched the top 5 DEXs, and among them, the contents of the 4 DEXs(KlaySwap, ClaimSwap, PalaDEX, definix), excluding a stable coin swap named Kokonut swap, are summarized below.

**Summary Klaytn DEX Research**
- KlaySwap is very different from other DEX contracts, and there is a separate `createFee` concept for LP creation.
- ClaimSwap, Pala DEX, and Definix use almost the same contract and have the similar interface. (Except for Definix liquidity supply function name… used as `addLiquidityETH`)
- There is no separate procedure for KlaySwap and Pala DEX to be listed on DEX. ClaimSwap (I guess, not confirmed yet by Claim swap team), Definix has a separate procedure.

**Conclusion**
- It can provide users with a common interface, but it cannot manage many DEXs as a single logic.
- The parts with differences between DEXs (fees, minimum quantity when supplying liquidity, deadline, etc.) seem difficult to be provided as a function parameter to users, and it seems possible to set a default value and subtract it as an option if necessary.
- If the SDK provides DEX-related functions, you need to add additional logic that you want to provide additional dex functions.
- The expected usability of the SDK is as follows. If a separate whitelisting process is required, a separate process is required.
```
caver.wallet.add(xxx)
await caver.dex.createKLAYPool(caver.dex.klayswap, tokenA_addr, tokenA_amount, klay_amount)
await caver.dex.createKCTPool(caver.dex.klayswap, tokenA_addr, tokenA_amount, tokenB_addr, tokenB_amount)
```

I will take a look pangea swap from next week. Please give a any feedback.

**Comment by jimni1222** [comment]
I share the findings of my research on providing the LP creation function.
- Klaytn
  - WhiteListing
    - ClaimSwap
    - Definix
  - Not WhiteListing
    - KlaySwap
    - PalaDEX
    - Pangea Swap - CPAMM
- Ethereum (Curve is a stable coin swap and is not subject to investigation)
  - WhiteListing
    - Uniswap v3 (whitelisting for token listings)
  - Not WhiteListing
    - Balancer
    
All of the above services can generate LP and provide initial liquidity on their website.
In addition, even if tokens or LPs were not publicly listed externally, most services (except Definix) were able to import the tokens manually and use tokens by users.

A number of services required a whitelisting process to publicly list LPs or tokens, and among them, I could only find a link to request a partnership on the ClaimSwap website.
Services that did not require whitelisting were providing users with a warning message or an indication that the token or LP was not verified.
For reference, KlaySwap brings up a safety notice popup when a user tries to deposit for all LPs.

In the case of Uniswap v3, the unit selected when depositing user liquidity is not LP, but each token pair.
And I thought whitelisting was necessary because only verified tokens are listed in the token list displayed in the dropdown.

**Comment by baerae-colin** [comment]
@jimni1222 Please give a presentation about what you have learn.

**Comment by jimni1222** [comment]
Purpose: To provide a function that facilitates the process of deploying KCT tokens, creating pools for DEXs, and supplying initial liquidity

Conclusion: Not provide

reason:
- Since V2 and V3 are very different, if we provide V2 usability mainly, users can use Klaytn's main stream DEXes right now, but if there is a DEX that uses a new protocol, it is impossible to cover it with a common interface (even with V3, there are many vague elements to provide as a common interface. existence)
- DEX of other ecosystems is not developing in one form, but in various forms for each service. In the case of Klaytn, famous projects from other ecosystems tend to fork → It is difficult to predict the shape of Klaytn DEX in the future
- All services provide the ability to create liquidity pools with UI on DEX sites.
- Each service has a different policy on whitelisting → It will be difficult for DApp developers to experience the experience we expect because each service has a different policy depending on what they want to pursue.
